### ISSUE TITLE
redux-saga error: uncaught

### ISSUE THREAD

**Issue by bmordan** [outlandishideas/kasia-boilerplate#1]
Having followed all the steps in the read me - I get this error

``` error
[1] ==> Kasia Boilerplate started at http://localhost:3000
[1] redux-saga error: uncaught
[1] at
[1]  Error: Not Found
[1]     at Request.callback (/Users/bernie/Code/wp-app/node_modules/superagent/lib/node/index.js:698:17)
[1]     at IncomingMessage.<anonymous> (/Users/bernie/Code/wp-app/node_modules/superagent/lib/node/index.js:922:12)
[1]     at emitNone (events.js:91:20)
[1]     at IncomingMessage.emit (events.js:185:7)
[1]     at endReadableNT (_stream_readable.js:926:12)
[1]     at _combinedTickCallback (internal/process/next_tick.js:74:11)
[1]     at process._tickCallback (internal/process/next_tick.js:98:9)
[1] ==> ROUTER ERROR:   Error: Not Found
```

![screen shot 2016-10-24 at 13 23 13](https://cloud.githubusercontent.com/assets/4499581/19645529/0ae7f972-99ed-11e6-97b1-f396b46afcc2.jpg)

**Comment by sdgluck** [comment]
In my experience this happens during server-side rendering when a requested resource cannot be found. Do your posts definitely have the right slugs as described in the README?

**Comment by bmordan** [comment]
![screen shot 2016-10-24 at 14 38 08](https://cloud.githubusercontent.com/assets/4499581/19647773/99c42a94-99f7-11e6-8c8f-8a12c3a35107.jpg)
![screen shot 2016-10-24 at 14 38 19](https://cloud.githubusercontent.com/assets/4499581/19647775/9c45938e-99f7-11e6-8ce4-0a96d4b08d18.jpg)

My `/src/config.js`

``` php
  host: process.env.HOST || 'localhost',
  wordpress: process.env.WORDPRESS || 'http://localhost/local-wordpress',
  wpapi: process.env.WORDPRESS_API || 'http://localhost/local-wordpress/wp-json',
  port: process.env.PORT || 3000,
```

My Local wordpress running

![screen shot 2016-10-24 at 14 42 09](https://cloud.githubusercontent.com/assets/4499581/19647896/178b608c-99f8-11e6-89f6-00e75626b026.jpg)

**Comment by sdgluck** [comment]
OK cool 👍 

Did you install WP somewhere other than at `localhost/wordpress`? 

Try to hit `http://<path_to_your_wp_installation>/wp-json/wp/v2/pages?slug=homepage` in your browser.

**Comment by sdgluck** [comment]
@bmordan Any luck?
